### ISSUE TITLE
npm polymorph demo broken

### ISSUE THREAD

**Issue by peterennis** [notoriousb1t/polymorph#17]
Maybe fix this with a new version release?
![capture1548](https://user-images.githubusercontent.com/140737/47931143-2d803f00-de8b-11e8-9c73-d9c6ecde6e77.PNG)
![capture1549](https://user-images.githubusercontent.com/140737/47931151-3113c600-de8b-11e8-99a2-6a9584f77572.PNG)

**Comment by notoriousb1t** [comment]
This should be fixed.  For some reason npm wasn't automatically linking to the gif.  I hardcoded the path to the head assets folder and it is showing up now. 

Thank you for letting me know :)
