### ISSUE TITLE
security vulnerabilities 63 low, 2 moderate, 7 high

### ISSUE THREAD

**Issue by peterennis** [notoriousb1t/polymorph#37]
![Capture608](https://user-images.githubusercontent.com/140737/60638750-6edb3c80-9dd4-11e9-90c6-fcfa33a64f62.png)

**Comment by peterennis** [comment]
fixed in this PR: https://github.com/notoriousb1t/polymorph/pull/36

all tests pass:

![Capture609](https://user-images.githubusercontent.com/140737/60638901-15274200-9dd5-11e9-87ee-4bf200d6f40e.png)

**Comment by peterennis** [comment]
@notoriousb1t 
I messed up the PR. Please ignore and I will create a new one without the baggage.

**Comment by notoriousb1t** [comment]
These security issues should only have an impact during development of polymorph not for developers who depend on it. Since the bundled file did not change, there is no reason to bump the version.

If you can undo the version bump and put my website link back in authors, I'll merge the PR.

**Comment by peterennis** [comment]
Done in this PR: https://github.com/notoriousb1t/polymorph/pull/39

**Comment by notoriousb1t** [comment]
Merged PR. Thank you for contributing :)
