### ISSUE TITLE
Unsupported element PATH

### ISSUE THREAD

**Issue by fluxxus** [notoriousb1t/polymorph#46]
I visited one site I built maybe half a year ago, only to see that some of the animations are not working anymore. 

I am pretty much sure that no changes to code were done. I am using `polymorph.js` in combo with `anime.js`. 

Including the library via script tag ` <script src="https://unpkg.com/polymorph-js/dist/polymorph.min.js"></script>`.

This is what I get in the console:

    Uncaught Error: Unsupported element  PATH
    at G (polymorph.min.js:4)
    at polymorph.min.js:88
    at new tr (polymorph.min.js:88)
    at polymorph.min.js:89
    at Array.map (<anonymous>)
    at Object.r.interpolate (polymorph.min.js:89)

**Comment by notoriousb1t** [comment]
I would guess based on that error that the code is using VDOM and that the new code which is checking for instanceof SVGPathElement fails due to the comparison being run on a virtual element. 

I changed the code to check tagName === 'PATH' like the last version used and moved the version to 1.0.1. Please let me know if this helps.  You may need to change the link to  `https://unpkg.com/browse/polymorph-js@1.0.1/dist/polymorph.min.js` to lock in the version (I am not sure how long unpkg caches for, so you may or may not need to do this).

Please let me know if this helps.

**Comment by fluxxus** [comment]
@notoriousb1t I am afraid it is still not working. I've cleared cache, checked in console that I am using the latest `1.0.1` version, but no luck.

I am linking to this file `https://unpkg.com/polymorph-js@1.0.1/dist/polymorph.min.js`

     Uncaught Error: Unsupported element  path
     at Z (polymorph.min.js:4)
     at polymorph.min.js:88
     at new tr (polymorph.min.js:88)
     at polymorph.min.js:89
     at Array.map (<anonymous>)
     at Object.r.interpolate (polymorph.min.js:89)

**Comment by notoriousb1t** [comment]
Could you provide a link to the site that is not working? I am afraid I can't help any further without something to debug. The tagName of Element should return in full uppercase (which is what all browsers should be doing).  The fact that it is in lowercase is a bit baffling.

The error is being thrown here: https://github.com/notoriousb1t/polymorph/blob/master/src/getPath.ts#L39.

**Comment by fluxxus** [comment]
Sure thing. Here is one part of the code from that website isolated without anything else. Guess it is easier for you this way, without stuff that is not needed.

[](https://www.zoric.design/test/polymorph/)

**Comment by notoriousb1t** [comment]
Okay, try `https://unpkg.com/polymorph-js@1.0.2/dist/polymorph.min.js'. It turns out I wasn't entirely right about tagName. It is in uppercase for HTML elements, but SVG elements aren't HTML elements, so they can be lowercase. I changed to code to be incase-sensitive.

**Comment by fluxxus** [comment]
All back to normal!

And I learned something along the way. Thanks :)
