### ISSUE TITLE
The path is getting NaN sometimes

### ISSUE THREAD

**Issue by EloB** [notoriousb1t/polymorph#58]
First of what a amazing library.

I written a codesandbox:
https://codesandbox.io/s/admiring-glade-d8n9y?file=/src/App.js

My sample here is getting `NaN` in the paths while clicking rapidly on the radio buttons. I made a simple console to show it.

Is this a bug?

**Comment by xavierfoucrier** [comment]
Hello @EloB 👋 

I am using this plugin a lot and discovered that if you do some optimizations using SVGO, the morphing can end with multiple `NaN` errors.

I guess it really depends on path optimizations.
